# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180322_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
