# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 12:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20180324_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=django.utils.crypto.get_random_string, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(db_index=True, default=False)),
                ('storytime', models.TextField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In-progress'), ('success', 'success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('reset_password', 'Reset-Password'), ('default', 'Default')], default='reset_password', max_length=16)),
                ('login_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authinvitations', to='business.LoginLink')),
            ],
            options={
                'verbose_name': 'Auth Invitation',
                'verbose_name_plural': 'Auth Invitations',
            },
        ),
    ]
